<?php

namespace App\Services;

use App\Models\Invoice;
use App\Support\DocumentTaxBreakdown;
use App\Support\LineItemCalculator;
use Illuminate\Support\Collection;

class CommercialDocumentTotalsService
{
    public function recalculateInvoice(Invoice $invoice): bool
    {
        if ($invoice->is_auto_generated && $invoice->pos_sale_id) {
            if ($this->syncAutoGeneratedInvoiceFromOrder($invoice)) {
                return true;
            }
        }

        $invoice->loadMissing('items');

        if ($invoice->items->isEmpty()) {
            return false;
        }

        $changed = false;
        $linesSubtotal = 0.0;

        foreach ($invoice->items as $item) {
            $unitPriceHt = LineItemCalculator::normalizeStoredUnitPriceToHt($item);

            $computed = LineItemCalculator::compute([
                'quantity' => $item->quantity,
                'unit_price' => $unitPriceHt,
                'tax_rate' => $item->tax_rate,
                'discount' => $item->discount ?? 0,
                'discount_type' => $item->discount_type ?? 'fixed',
            ]);

            $newLineTotal = $computed['line_total'];
            $linesSubtotal += $newLineTotal;

            $itemUpdates = [];

            if (round((float) $item->unit_price, 2) !== round($unitPriceHt, 2)) {
                $itemUpdates['unit_price'] = $unitPriceHt;
            }

            if (round((float) $item->line_total, 2) !== round($newLineTotal, 2)) {
                $itemUpdates['line_total'] = $newLineTotal;
            }

            if ($itemUpdates !== []) {
                $item->update($itemUpdates);
                $changed = true;
            }
        }

        $taxes = DocumentTaxBreakdown::fromDocument($invoice, $invoice->items()->get());
        $newSubtotal = round($linesSubtotal, 2);
        $newTotal = $taxes['total_ttc'];

        if (
            round((float) $invoice->subtotal, 2) !== $newSubtotal
            || round((float) $invoice->total, 2) !== $newTotal
        ) {
            $invoice->update([
                'subtotal' => $newSubtotal,
                'total' => $newTotal,
            ]);
            $changed = true;
        }

        if ($changed) {
            $invoice->syncPaymentStatus();
        }

        return $changed;
    }

    /**
     * Re-sync line items from the source POS order for legacy auto-generated invoices
     * that stored HT unit prices as TTC during conversion.
     */
    public function syncAutoGeneratedInvoiceFromOrder(Invoice $invoice): bool
    {
        if (! $invoice->is_auto_generated || ! $invoice->pos_sale_id) {
            return false;
        }

        $order = $invoice->posSale()->with('items.product')->first();
        if (! $order) {
            return false;
        }

        $invoice->loadMissing('items');

        if ($invoice->items->isEmpty() || $order->items->isEmpty()) {
            return false;
        }

        if (round((float) $invoice->total, 2) === round((float) $order->total, 2)) {
            return false;
        }

        $orderItems = $order->items->values();
        $invoiceItems = $invoice->items->values();

        if ($orderItems->count() !== $invoiceItems->count()) {
            return false;
        }

        $changed = false;
        $linesSubtotal = 0.0;

        foreach ($orderItems as $index => $orderItem) {
            $invoiceItem = $invoiceItems[$index];
            $unitPriceHt = LineItemCalculator::normalizeStoredUnitPriceToHt($orderItem);
            $lineTotal = round((float) $orderItem->line_total, 2);

            $itemUpdates = [
                'unit_price' => $unitPriceHt,
                'tax_rate' => $orderItem->tax_rate ?? 20,
                'discount' => $orderItem->discount ?? 0,
                'discount_type' => 'fixed',
                'line_total' => $lineTotal,
            ];

            $linesSubtotal += $lineTotal;

            $needsUpdate = false;
            foreach ($itemUpdates as $field => $value) {
                if (round((float) $invoiceItem->{$field}, 2) !== round((float) $value, 2)) {
                    $needsUpdate = true;
                    break;
                }
            }

            if ($needsUpdate) {
                $invoiceItem->update($itemUpdates);
                $changed = true;
            }
        }

        $invoiceUpdates = [
            'subtotal' => round($linesSubtotal, 2),
            'discount' => $order->discount,
            'total' => round((float) $order->total, 2),
        ];

        $headerChanged = false;
        foreach ($invoiceUpdates as $field => $value) {
            if (round((float) $invoice->{$field}, 2) !== round((float) $value, 2)) {
                $headerChanged = true;
                break;
            }
        }

        if ($headerChanged) {
            $invoice->update($invoiceUpdates);
            $changed = true;
        }

        if ($changed) {
            $invoice->syncPaymentStatus();
        }

        return $changed;
    }

    /**
     * @return array{processed: int, updated: int}
     */
    public function recalculateAllInvoices(): array
    {
        $processed = 0;
        $updated = 0;

        Invoice::query()->with('items')->chunkById(100, function (Collection $invoices) use (&$processed, &$updated) {
            foreach ($invoices as $invoice) {
                $processed++;
                if ($this->recalculateInvoice($invoice)) {
                    $updated++;
                }
            }
        });

        return compact('processed', 'updated');
    }
}
