<?php

namespace App\Services;

use App\Models\Invoice;
use App\Models\InvoiceItem;
use App\Models\InvoicePayment;
use App\Models\PosSale;
use App\Models\Setting;
use App\Support\DocumentTaxBreakdown;
use App\Support\LineItemCalculator;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\ValidationException;

class OrderToInvoiceConverter
{
    public function invoiceExistsForOrder(PosSale $order): bool
    {
        return Invoice::query()->where('pos_sale_id', $order->id)->exists();
    }

    public function shouldAutoGenerate(PosSale $order): bool
    {
        if ($order->payment_status !== 'paid' || $order->fulfillment_status !== 'fulfilled') {
            return false;
        }

        if (! $order->client_id) {
            return false;
        }

        $startNumber = Setting::get('auto_invoice_start_order_number');
        if ($startNumber === null || $startNumber === '') {
            return false;
        }

        $orderNumber = $this->extractOrderNumber($order->ticket_number);
        if ($orderNumber === null) {
            return false;
        }

        return $orderNumber >= (int) $startNumber;
    }

    public function tryAutoGenerate(PosSale $order): ?Invoice
    {
        if (! $this->shouldAutoGenerate($order) || $this->invoiceExistsForOrder($order)) {
            return null;
        }

        return $this->convert($order, markAsPaid: true, autoGenerated: true);
    }

    public function convert(PosSale $order, bool $markAsPaid = false, bool $autoGenerated = false): Invoice
    {
        if ($this->invoiceExistsForOrder($order)) {
            throw new \RuntimeException('Une facture existe déjà pour cette commande.');
        }

        if (! $order->client_id) {
            throw new \RuntimeException('La commande n\'a pas de client associé.');
        }

        $order->loadMissing('items.product', 'assignedUser');

        $collaboratorId = $order->assignedUser?->collaborator_id;

        $invoice = Invoice::create([
            'invoice_number' => DocumentNumberService::generate('facture'),
            'client_id' => $order->client_id,
            'collaborator_id' => $collaboratorId,
            'created_by_user_id' => auth()->id() ?? $order->created_by_user_id,
            'pos_sale_id' => $order->id,
            'is_auto_generated' => $autoGenerated,
            'invoice_date' => now(),
            'due_date' => now()->addDays(30),
            'currency' => $this->normalizeCurrency($order->currency),
            'stock_location' => $this->defaultStockLocation($order),
            'subtotal' => 0,
            'discount' => $order->discount,
            'adjustment' => 0,
            'total' => 0,
            'remarks' => 'Générée automatiquement depuis la commande ' . $order->ticket_number,
            'conditions' => Setting::get('facture_conditions'),
            // Statut réel = paiements affectés (InvoicePayment), pas un flag manuel.
            'payment_status' => Invoice::PAYMENT_UNPAID,
            'commercial_status' => 'normal',
            'source' => $order->source,
        ]);

        $linesSubtotal = 0.0;

        foreach ($order->items as $item) {
            $unitPriceHt = LineItemCalculator::normalizeStoredUnitPriceToHt($item);
            $computed = LineItemCalculator::compute([
                'quantity' => $item->quantity,
                'unit_price' => $unitPriceHt,
                'tax_rate' => $item->tax_rate ?? 20,
                'discount' => $item->discount ?? 0,
                'discount_type' => 'fixed',
            ]);

            InvoiceItem::create([
                'itemable_type' => Invoice::class,
                'itemable_id' => $invoice->id,
                'product_id' => $item->product_id,
                'ref' => $item->ref ?? $item->product?->ref,
                'designation' => $item->designation ?? $item->product?->name,
                'description' => $item->product?->description,
                'quantity' => $item->quantity,
                'unit_price' => $unitPriceHt,
                'tax_rate' => $item->tax_rate ?? 20,
                'discount' => $item->discount ?? 0,
                'discount_type' => 'fixed',
                'line_total' => $computed['line_total'],
            ]);

            $linesSubtotal += $computed['line_total'];
        }

        $shippingAmount = round((float) ($order->shipping_amount ?? 0), 2);
        if ($shippingAmount > 0.009) {
            InvoiceItem::create([
                'itemable_type' => Invoice::class,
                'itemable_id' => $invoice->id,
                'product_id' => null,
                'ref' => 'LIVRAISON',
                'designation' => 'Frais de livraison',
                'description' => 'Livraison facturée au client',
                'quantity' => 1,
                'unit_price' => $shippingAmount,
                'tax_rate' => 0,
                'discount' => 0,
                'discount_type' => 'fixed',
                'line_total' => $shippingAmount,
            ]);

            $linesSubtotal += $shippingAmount;
        }

        $taxes = DocumentTaxBreakdown::fromDocument($invoice, $invoice->items()->get());

        $invoice->update([
            'subtotal' => round($linesSubtotal, 2),
            'total' => $taxes['total_ttc'],
        ]);

        $invoice = $invoice->fresh('items');
        app(\App\Services\Access\CommissionService::class)->syncForInvoice($invoice);

        if ($markAsPaid || $order->payment_status === 'paid' || $this->orderHasRecordedPayment($order)) {
            $this->attachOrderPayment($invoice, $order, $markAsPaid);
        }

        return $invoice->fresh(['items', 'payments']);
    }

    /**
     * Lie un paiement réel (InvoicePayment) à la facture à partir de la commande payée.
     * Un mouvement financier seul ne suffit pas : c’est cette affectation qui met à jour
     * Montant payé / Reste / statut PAYÉE et retire la facture des Impayés.
     */
    public function attachOrderPayment(Invoice $invoice, PosSale $order, bool $forceFullRemaining = false): ?InvoicePayment
    {
        $invoice->loadMissing(['items', 'payments', 'posSale']);
        $remaining = round($invoice->collectibleRemainingBalance(), 2);
        if ($remaining <= 0.009) {
            $invoice->syncPaymentStatus();

            return null;
        }

        $amount = $this->resolvePaymentAmount($order, $remaining, $forceFullRemaining);
        if ($amount <= 0.009) {
            $invoice->syncPaymentStatus();

            return null;
        }

        $method = $order->paymentLabel() ?: 'Carte bancaire';
        $paymentDate = ($order->sold_at ?? now())->toDateString();
        $reference = $order->ticket_number;

        try {
            return app(PaymentRecordingService::class)->recordInvoicePayment($invoice, [
                'payment_date' => $paymentDate,
                'amount' => $amount,
                'gross_amount' => $amount,
                'payment_method' => $method,
                'payment_reference' => $reference,
                'notes' => 'Paiement commande '.$order->ticket_number,
                'source' => InvoicePayment::SOURCE_ORDER,
                'pos_sale_id' => $order->id,
                'tracking_number' => $order->primaryTrackingNumber(),
                'dedupe_key' => app(PaymentRecordingService::class)->buildDedupeKey([
                    'scope' => 'sales',
                    'invoice_id' => $invoice->id,
                    'reference' => $reference,
                    'amount' => $amount,
                    'date' => $paymentDate,
                    'method' => $method,
                    'source' => InvoicePayment::SOURCE_ORDER,
                    'pos_sale_id' => $order->id,
                ]),
            ]);
        } catch (ValidationException $e) {
            // Anti-doublon / facture déjà soldée : resynchroniser le statut sans planter la conversion.
            Log::info('Order payment already allocated or invoice settled', [
                'invoice_id' => $invoice->id,
                'pos_sale_id' => $order->id,
                'messages' => $e->errors(),
            ]);
            $invoice->refresh();
            $invoice->syncPaymentStatus();

            return null;
        }
    }

    protected function orderHasRecordedPayment(PosSale $order): bool
    {
        if ((float) ($order->amount_received ?? 0) > 0.009) {
            return true;
        }

        return in_array($order->payment_status, ['paid', 'partially_paid'], true);
    }

    protected function resolvePaymentAmount(PosSale $order, float $remaining, bool $forceFullRemaining = false): float
    {
        $received = round((float) ($order->amount_received ?? 0), 2);
        if ($received > 0.009) {
            return min($remaining, $received);
        }

        if ($forceFullRemaining || $order->payment_status === 'paid') {
            return $remaining;
        }

        return 0.0;
    }

    protected function defaultStockLocation(PosSale $order): string
    {
        return match ($order->source) {
            'shopify' => 'Stock en ligne',
            'jumia' => 'Stock en ligne',
            default => 'Stock magasin',
        };
    }

    public function extractOrderNumber(string $ticketNumber): ?int
    {
        if (preg_match('/(\d+)\s*$/', trim($ticketNumber), $matches)) {
            return (int) $matches[1];
        }

        return null;
    }

    private function normalizeCurrency(?string $currency): string
    {
        if ($currency === null || $currency === '') {
            return 'dh - MAD';
        }

        if (str_contains(strtoupper($currency), 'MAD')) {
            return 'dh - MAD';
        }

        return $currency;
    }
}
