<?php

namespace Tests\Unit;

use App\Models\Client;
use App\Models\Invoice;
use App\Models\PosSale;
use App\Models\PosSaleItem;
use App\Models\Setting;
use App\Services\OrderToInvoiceConverter;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class OrderToInvoiceConverterTest extends TestCase
{
    use RefreshDatabase;

    public function test_auto_generated_invoice_stores_ht_unit_price_and_correct_ttc_totals(): void
    {
        Setting::set('shopify_price_type', 'ttc');

        $client = Client::create(['name' => 'Auto Client']);
        $order = PosSale::create([
            'ticket_number' => 'POS-2026/000099',
            'client_id' => $client->id,
            'sold_at' => now(),
            'currency' => 'dh - MAD',
            'subtotal' => 583.33,
            'discount' => 0,
            'tax_total' => 116.67,
            'total' => 700,
            'payment_method' => 'cash',
            'status' => 'completed',
            'payment_status' => 'paid',
            'fulfillment_status' => 'fulfilled',
        ]);

        PosSaleItem::create([
            'pos_sale_id' => $order->id,
            'designation' => 'Produit POS',
            'quantity' => 1,
            'unit_price' => 700,
            'tax_rate' => 20,
            'discount' => 0,
            'line_total' => 700,
        ]);

        $invoice = app(OrderToInvoiceConverter::class)->convert($order, autoGenerated: true);

        $invoice->load('items');

        $this->assertTrue($invoice->is_auto_generated);
        $this->assertEquals(583.33, (float) $invoice->items->first()->unit_price);
        $this->assertEquals(700.0, (float) $invoice->items->first()->line_total);
        $this->assertEquals(700.0, (float) $invoice->total);
        $this->assertEquals(700.0, $invoice->computed_total);
    }

    public function test_convert_order_with_ht_unit_prices_preserves_ttc_total(): void
    {
        Setting::set('shopify_price_type', 'ttc');

        $client = Client::create(['name' => 'POS Client']);
        $order = PosSale::create([
            'ticket_number' => 'POS-2026/000100',
            'client_id' => $client->id,
            'sold_at' => now(),
            'currency' => 'dh - MAD',
            'subtotal' => 358.33,
            'discount' => 0,
            'tax_total' => 71.67,
            'total' => 430,
            'payment_method' => 'cash',
            'status' => 'completed',
            'payment_status' => 'paid',
            'fulfillment_status' => 'fulfilled',
        ]);

        PosSaleItem::create([
            'pos_sale_id' => $order->id,
            'designation' => 'Produit POS',
            'quantity' => 1,
            'unit_price' => 358.33,
            'tax_rate' => 20,
            'discount' => 0,
            'line_total' => 430,
        ]);

        $invoice = app(OrderToInvoiceConverter::class)->convert($order);

        $invoice->load('items');

        $this->assertEquals(358.33, (float) $invoice->items->first()->unit_price);
        $this->assertEquals(430.0, (float) $invoice->items->first()->line_total);
        $this->assertEquals(430.0, (float) $invoice->total);
        $this->assertEquals(430.0, $invoice->computed_total);
    }

    public function test_convert_includes_client_shipping_as_invoice_line(): void
    {
        Setting::set('shopify_price_type', 'ttc');

        $client = Client::create(['name' => 'Shipping Client']);
        $order = PosSale::create([
            'ticket_number' => 'FAST12445',
            'client_id' => $client->id,
            'sold_at' => now(),
            'currency' => 'dh - MAD',
            'subtotal' => 93.33,
            'discount' => 0,
            'tax_total' => 18.67,
            'shipping_amount' => 40,
            'total' => 152,
            'payment_method' => 'cash',
            'status' => 'completed',
            'payment_status' => 'unpaid',
            'fulfillment_status' => 'fulfilled',
        ]);

        PosSaleItem::create([
            'pos_sale_id' => $order->id,
            'designation' => 'Produit',
            'quantity' => 1,
            'unit_price' => 93.33,
            'tax_rate' => 20,
            'discount' => 0,
            'line_total' => 112,
        ]);

        $invoice = app(OrderToInvoiceConverter::class)->convert($order);
        $invoice->load('items');

        $this->assertCount(2, $invoice->items);
        $shippingLine = $invoice->items->firstWhere('ref', 'LIVRAISON');
        $this->assertNotNull($shippingLine);
        $this->assertEquals(40.0, (float) $shippingLine->line_total);
        $this->assertEquals(152.0, (float) $invoice->total);
        $this->assertEquals(152.0, $invoice->computed_total);
        $this->assertEquals(152.0, $invoice->collectibleTotal());
    }

    public function test_convert_skips_shipping_line_when_free_delivery(): void
    {
        Setting::set('shopify_price_type', 'ttc');

        $client = Client::create(['name' => 'Free Ship Client']);
        $order = PosSale::create([
            'ticket_number' => 'FAST12446',
            'client_id' => $client->id,
            'sold_at' => now(),
            'currency' => 'dh - MAD',
            'subtotal' => 93.33,
            'discount' => 0,
            'tax_total' => 18.67,
            'shipping_amount' => 0,
            'total' => 112,
            'payment_method' => 'cash',
            'status' => 'completed',
            'payment_status' => 'unpaid',
            'fulfillment_status' => 'fulfilled',
        ]);

        PosSaleItem::create([
            'pos_sale_id' => $order->id,
            'designation' => 'Produit',
            'quantity' => 1,
            'unit_price' => 93.33,
            'tax_rate' => 20,
            'discount' => 0,
            'line_total' => 112,
        ]);

        $invoice = app(OrderToInvoiceConverter::class)->convert($order);
        $invoice->load('items');

        $this->assertCount(1, $invoice->items);
        $this->assertNull($invoice->items->firstWhere('ref', 'LIVRAISON'));
        $this->assertEquals(112.0, $invoice->collectibleTotal());
    }
}
